FROM node:20-bullseye-slim

WORKDIR /app
RUN apt update
RUN apt -y upgrade
RUN apt install -y git
#RUN git clone https://github.com/noatgnu/turnoverAtlasNG.git
COPY . /app/CinderFrontend
WORKDIR /app/CinderFrontend
#RUN sed -i 's;https://turnoveratlas.omics.quest;http://localhost;g' src/environments/environment.ts
RUN npm install
RUN npm run build

FROM nginx:latest

COPY --from=0 /app/CinderFrontend/dist/browser /usr/share/nginx/html

EXPOSE 80
